Repository mobileappdevhm/team2, pull requests merged in 2018-06, with the labels that each got.

#101 Coveralls
  .travis.yml
  README.md
Labels: review required

#106 Settings screen
  lib/connect/dataprovider/data.dart
  lib/connect/dataprovider/mock_provider_factory.dart
  lib/connect/dataprovider/provider_factory.dart
  lib/connect/dataprovider/sqlite_data.dart
  lib/connect/dataprovider/sqlite_provider_factory.dart
  lib/connect/dataprovider/user/mock/mock_user_settings_provider.dart
  lib/connect/dataprovider/user/user_settings_provider.dart
  lib/model/user/user_settings.dart
  lib/ui/basic_components/line_separator.dart
  lib/ui/scaffolds/bnb_home.dart
  lib/ui/screens/settings_screen.dart
  test/settings_screen_test.dart
Labels: basic features

#114 Filtering / search function
  lib/ui/scaffolds/bnb_home.dart
  lib/ui/screens/course_list_screen.dart
  lib/ui/screens/favorites_screen.dart
  pubspec.yaml
Labels: high priority

#107 Timtable upgrade
  android/app/src/main/AndroidManifest.xml
  lib/connect/dataprovider/course/course_provider.dart
  lib/connect/dataprovider/mock_data.dart
  lib/controller/session.dart
  lib/ics_creator.dart
  lib/model/course/time_and_day.dart
  lib/model/timetable/timtable_course.dart
  lib/ui/basic_components/availability_widget.dart
  lib/ui/basic_components/course_list_entry.dart
  lib/ui/basic_components/timetable_entry.dart
  lib/ui/scaffolds/bnb_home.dart
  lib/ui/scaffolds/course_details.dart
  lib/ui/screens/timetable_screen.dart
  pubspec.yaml
  test/data_test.dart
  test/home_screen_test.dart
Labels: help wanted, high priority

#119 TestyMcTestFace
  test/availability_widget_test.dart
  test/course_details_test.dart
  test/course_list_entry_test.dart
  test/course_list_test.dart
  test/favorites_screen_test.dart
  test/home_screen_test.dart
  test/location_test.dart
  test/timetable_test.dart
Labels: in progress

#117 Cie course tracking
  android/build.gradle
  lib/connect/dataprovider/campus/sqlite_campus_provider.dart
  lib/connect/dataprovider/cie/cie_provider.dart
  lib/connect/dataprovider/cie/mock/sqlite_cie_provider.dart
  lib/connect/dataprovider/course/sqlite_course_provider.dart
  lib/connect/dataprovider/databasehelper/databasehelper.dart
  lib/connect/dataprovider/lecturer/sqlite_lecturer_provider.dart
  lib/model/cie/cie.dart
  lib/ui/basic_components/cie_list_entry.dart
  lib/ui/screens/add_cie_screen.dart
  lib/ui/screens/cie_screen.dart
  lib/ui/screens/settings_screen.dart
  test/add_cie_test.dart
  test/availability_widget_test.dart
  test/cie_screen_test.dart
  test/course_details_test.dart
  test/course_list_entry_test.dart
  test/course_list_test.dart
  test/favorites_screen_test.dart
  test/home_screen_test.dart
  test/location_test.dart
  test/settings_screen_test.dart
  test/timetable_test.dart
Labels: in progress

#121 DEPLOY
  .travis.yml
Labels: in progress

#138 Added cow icons
  res/cow-icon/Zeichenfläche 1.svg
  res/cow-icon/Zeichenfläche 1hdpi.png
  res/cow-icon/Zeichenfläche 1ldpi.png
  res/cow-icon/Zeichenfläche 1mdpi.png
  res/cow-icon/Zeichenfläche 1xhdpi.png
  res/cow-icon/Zeichenfläche 1xxhdpi.png
  res/cow-icon/Zeichenfläche 1xxxhdpi.png
Labels: in progress

#123 Added link to google maps
  lib/connect/dataprovider/campus/sqlite_campus_provider.dart
  lib/connect/dataprovider/databasehelper/databasehelper.dart
  lib/connect/dataprovider/mock_data.dart
  lib/model/campus/campus.dart
  lib/ui/screens/locations_screen.dart
  test/sql_test.dart
Labels: in progress

#157 removed loignScreen from stack when logged in
  lib/ui/scaffolds/login.dart
  test/settings_screen_test.dart
Labels: in progress

#151 Clear search
  lib/ui/scaffolds/bnb_home.dart
Labels: in progress

#154 locked orientation to portrait
  lib/main.dart
  test/settings_screen_test.dart
Labels: in progress

#160 error fixes
  lib/connect/dataprovider/cie/mock/mock_cie_provider.dart
  lib/connect/dataprovider/cie/mock/sqlite_cie_provider.dart
  lib/controller/session.dart
  lib/ui/screens/cie_screen.dart
Labels: in progress

#159 Making Session testable
  lib/connect/dataprovider/mock_data.dart
  lib/connect/dataprovider/mockito_provider_factory.dart
  lib/connect/dataprovider/user/mock/mock_user_provider.dart
  lib/controller/session.dart
  lib/main.dart
  lib/model/user/user.dart
  lib/ui/scaffolds/course_details.dart
  test/session_test.dart
  test/sql_test.dart
Labels: in progress

#163 Filter departments
  lib/ui/scaffolds/bnb_home.dart
Labels: in progress

#165 Make test coverage great again
  lib/controller/user_creation_controller.dart
  lib/main.dart
  lib/model/cie/cie.dart
  lib/model/course/course.dart
  lib/ui/scaffolds/add_cie.dart
  lib/ui/scaffolds/create_user.dart
  lib/ui/scaffolds/login.dart
  pubspec.yaml
  test/unit_tests/controller/content_controller_test.dart
  test/unit_tests/model/campus_test.dart
  test/unit_tests/model/course_test.dart
  test/unit_tests/model/department_test.dart
  test/unit_tests/model/lecturer_test.dart
  test/unit_tests/model/user_test.dart
  test/widget_tests/add_cie_test.dart
  test/widget_tests/cie_screen_test.dart
  test/widget_tests/components/availability_widget_test.dart
  test/widget_tests/components/cie_list_entry_test.dart
  test/widget_tests/components/course_list_entry_test.dart
  test/widget_tests/home_screen_test.dart
  test/widget_tests/login_test.dart
  test/widget_tests/scaffolds/add_cie_test.dart
  test/widget_tests/scaffolds/course_details_test.dart
  test/widget_tests/scaffolds/home_scaffold_test.dart
  test/widget_tests/scaffolds/login_test.dart
  test/widget_tests/screens/cie_screen_test.dart
  test/widget_tests/screens/course_list_test.dart
  test/widget_tests/screens/favorites_screen_test.dart
  test/widget_tests/screens/location_test.dart
  test/widget_tests/screens/settings_screen_test.dart
  test/widget_tests/screens/timetable_test.dart
  test/widget_tests/settings_screen_test.dart
Labels: in progress

#164 Firebase analytics
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/edu/hm/cs/mobileappdev/team2/MainActivity.java
  lib/controller/cie_controller.dart
  lib/controller/content_controller.dart
  lib/controller/favorites_controller.dart
  lib/controller/firebase/fb_cie_controller.dart
  lib/controller/firebase/fb_favorites_controller.dart
  lib/controller/firebase/fb_session_controller.dart
  lib/controller/firebase/firebase_controller.dart
  lib/controller/injector.dart
  lib/controller/normal/cie_controller.dart
  lib/controller/normal/content_controller.dart
  lib/controller/normal/favorites_controller.dart
  lib/controller/normal/ics_creator.dart
  lib/controller/normal/session_controller.dart
  lib/controller/normal/settings_controller.dart
  lib/controller/session_controller.dart
  lib/controller/settings_controller.dart
  lib/io/cache/in_memory_provider_factory.dart
  lib/io/cache/providers/in_memory/inmem_campus_provider.dart
  lib/io/cache/providers/in_memory/inmem_cie_provider.dart
  lib/io/cache/providers/in_memory/inmem_custom_course_provider.dart
  lib/io/cache/providers/in_memory/inmem_department_provider.dart
  lib/io/cache/providers/in_memory/inmem_lecturer_provider.dart
  lib/io/cache/providers/in_memory/inmem_user_provider.dart
  lib/io/cache/providers/in_memory/inmem_user_settings_provider.dart
  lib/io/cache/providers/sqlite/sqlite_course_provider.dart
  lib/io/cache/providers/sqlite/sqlite_custom_course_provider.dart
  lib/io/cache/providers/user_provider.dart
  lib/io/inet/mock_inet_provider_factory.dart
  lib/io/inet/mockito_inet_provider_factory.dart
  lib/io/inet/providers/mock/mock_department_provider.dart
  lib/io/inet/providers/mock/mock_user_provider.dart
  lib/io/inet/providers/user_provider.dart
  lib/main.dart
  lib/model/user/user_settings.dart
  lib/ui/basic_components/cie_list_entry.dart
  lib/ui/basic_components/course_list_entry.dart
  lib/ui/basic_components/line_separator.dart
  lib/ui/scaffolds/add_cie.dart
  lib/ui/scaffolds/bnb_home.dart
  lib/ui/scaffolds/course_details.dart
  lib/ui/scaffolds/loading.dart
  lib/ui/scaffolds/login.dart
  lib/ui/screens/cie_screen.dart
  lib/ui/screens/course_list_screen.dart
  lib/ui/screens/favorites_screen.dart
  lib/ui/screens/settings_screen.dart
  pubspec.yaml
  test/unit_tests/controller/content_controller_test.dart
  test/unit_tests/controller/favorites_controller_test.dart
  test/widget_tests/scaffolds/add_cie_test.dart
  test/widget_tests/scaffolds/course_details_test.dart
  test/widget_tests/scaffolds/home_scaffold_test.dart
  test/widget_tests/scaffolds/login_test.dart
  test/widget_tests/screens/cie_screen_test.dart
  test/widget_tests/screens/settings_screen_test.dart
Labels: in progress

#166 About notice and GDPR notices
  lib/ui/basic_components/rounded_button.dart
  lib/ui/scaffolds/gdpr_notice.dart
  lib/ui/screens/settings_screen.dart
Labels: in progress

#169 Search bug
  lib/ui/scaffolds/bnb_home.dart
Labels: in progress

#170 Changing look and feel
  .travis.yml
  lib/model/course/time_and_day.dart
  lib/ui/basic_components/cie_list_entry.dart
  lib/ui/basic_components/course_list_entry.dart
  lib/ui/basic_components/timetable_entry.dart
  lib/ui/screens/settings_screen.dart
Labels: in progress

#171 Communication with server
  README.md
  lib/io/inet/http/http_helper.dart
  lib/io/inet/http/prod_http_helper.dart
  lib/io/inet/prod_provider_factory.dart
  lib/io/inet/providers/prod/campus_provider.dart
  lib/io/inet/providers/prod/course_provider.dart
  lib/io/inet/providers/prod/custom_course_provider.dart
  lib/io/inet/providers/prod/department_provider.dart
  lib/io/inet/providers/prod/lecturer_provider.dart
  lib/io/inet/providers/prod/user_provider.dart
  lib/main.dart
  lib/model/campus/campus.dart
  lib/model/course/course.dart
  lib/model/lecturer/lecturer.dart
  lib/ui/basic_components/course_list_entry.dart
  lib/ui/scaffolds/course_details.dart
  pubspec.yaml
  test/unit_tests/model/course_test.dart
Labels: in progress

#177 Password reset
  lib/controller/firebase/fb_session_controller.dart
  lib/controller/normal/session_controller.dart
  lib/controller/session_controller.dart
  lib/io/inet/http/http_helper.dart
  lib/io/inet/http/prod_http_helper.dart
  lib/io/inet/providers/mock/mock_user_provider.dart
  lib/io/inet/providers/prod/user_provider.dart
  lib/io/inet/providers/user_provider.dart
  lib/ui/basic_components/my_dropdown_button.dart
  lib/ui/basic_components/rounded_button.dart
  lib/ui/scaffolds/login.dart
  lib/ui/scaffolds/password_reset.dart
  lib/ui/scaffolds/request_password_reset.dart
  test/unit_tests/controller/favorites_controller_test.dart
  test/unit_tests/model/campus_test.dart
  test/unit_tests/model/course_test.dart
  test/unit_tests/model/department_test.dart
  test/unit_tests/model/lecturer_test.dart
  test/unit_tests/model/user_test.dart
  test/unit_tests/sql_test.dart
  test/widget_tests/components/cie_list_entry_test.dart
  test/widget_tests/scaffolds/add_cie_test.dart
  test/widget_tests/scaffolds/course_details_test.dart
  test/widget_tests/scaffolds/home_scaffold_test.dart
  test/widget_tests/scaffolds/login_test.dart
  test/widget_tests/scaffolds/password_reset_request_test.dart
  test/widget_tests/scaffolds/password_reset_test.dart
  test/widget_tests/screens/cie_screen_test.dart
  test/widget_tests/screens/settings_screen_test.dart
Labels: in progress

#178 Visual fixes + some network stuff
  lib/io/inet/http/http_helper.dart
  lib/io/inet/http/prod_http_helper.dart
  lib/io/inet/providers/prod/campus_provider.dart
  lib/io/inet/providers/prod/course_provider.dart
  lib/io/inet/providers/prod/department_provider.dart
  lib/io/inet/providers/prod/lecturer_provider.dart
  lib/io/inet/providers/prod/user_provider.dart
  lib/model/campus/campus.dart
  lib/model/course/course.dart
  lib/model/department/department.dart
  lib/model/lecturer/lecturer.dart
  lib/ui/basic_components/course_list_entry.dart
  lib/ui/scaffolds/bnb_home.dart
  lib/ui/scaffolds/course_details.dart
  lib/ui/scaffolds/login.dart
  lib/ui/screens/timetable_screen.dart
  test/widget_tests/screens/settings_screen_test.dart
Labels: in progress

#187 Added firebase to normal project
  android/app/google-services.json
Labels: in progress
