Repository mobileappdevhm/team2, pull requests merged in 2018-05, with the labels that each got.

#31 Forbid usage of capital letters in file names
  .no_camel.sh
  .travis.yml
  lib/main.dart
  lib/ui/scaffolds/bnb_home.dart
  lib/ui/screens/sample_screen.dart
Labels: review required

#35 Details page
  lib/connect/dataprovider/data.dart
  lib/connect/dataprovider/favorites/favorites_provider.dart
  lib/connect/dataprovider/favorites/mock/mock_favorites_provider.dart
  lib/connect/dataprovider/mock_provider_factory.dart
  lib/connect/dataprovider/provider_factory.dart
  lib/ui/scaffolds/bnb_home.dart
  lib/ui/scaffolds/course_details.dart
  lib/ui/screens/sample_course_list.dart
Labels: review required

#42 Fixed Gitignore
  .gitignore
  pubspec.yaml
Labels: enhancement

#73 Mvc
  lib/main.dart
  lib/ui/scaffolds/bnb_home.dart
  lib/ui/scaffolds/dwr_home.dart
  lib/ui/scaffolds/login.dart
  lib/ui/screens/course_list_screen.dart
  lib/ui/screens/locations_screen.dart
  lib/ui/screens/timetable_screen.dart
Labels: high priority, review required

#74 Tests
  test/data_test.dart
  test/home_screen_test.dart
  test/widget_test.dart
Labels: review required, tests

#79 Trying to fix deployment job
  .travis.yml
Labels: high priority

#80 Added gradle
  .travis.yml
Labels: bug

#93 Added option for bold seperator
  lib/ui/basic_components/line_separator.dart
Labels: enhancement
